GAME_DATA = {
    "Valorant": {
        "characters": [
            "Brimstone",
            "Omen",
            "Viper",
            "Raze",
            "Cypher",
            "Sage",
            "Sova",
            "Phoenix",
            "Jett",
            "Breach",
            "Reyna",
            "Killjoy",
            "Skye",
            "Yoru",
            "Astra",
            "KAY-O",
            "Chamber",
            "Neon",
            "Fade",
            "Harbor",
            "Gekko",
            "Deadlock",
            "Iso",
            "Clove",
            "Vyse",
            "Tejo",
            "Waylay"
            ],
        "maps" : [
            "Sunset",
            "Lotus",
            "Pearl",
            "Fracture",
            "Breeze",
            "Icebox",
            "Bind",
            "Haven",
            "Split",
            "Ascent"
        ],
        "roles": ["Duelist", "Initiator", "Sentinel", "Controller"],
        "char_to_role": [3,3,3,0,2,2,1,0,0,1,0,2,1,0,3,1,2,0,1,3,2,2,0,3,2,1,0]
    },
    "Marvel Rivals":{
        "characters": [
            "Hulk",
            "Captain America",
            "Doctor Strange",
            "Groot",
            "Magneto",
            "Peni Parker",
            "The Thing",
            "Thor",
            "Venom",
            "Black Panther",
            "Black Widow",
            "Hawkeye",
            "Hela",
            "Human Torch",
            "Iron Fist",
            "Iron Man",
            "Magik",
            "Mister Fantastic",
            "Moon Knight",
            "Namor",
            "Psylocke",
            "Punisher",
            "Scarlet Witch",
            "Spider-Man",
            "Squirrel Girl",
            "Star-Lord",
            "Storm",
            "Winter Soldier",
            "Wolverine",
            "Adam Warlock",
            "Cloak and Dagger",
            "Invisible Woman",
            "Jeff the Land Shark",
            "Loki",
            "Luna Snow",
            "Mantis",
            "Rocket Raccoon"
        ],
        "maps" : [
            "Central Park",
            "Hall of Djalia",
            "Symbiotic Surface",
            "Shin-Shibuya",
            "Midtown",
            "Spider-Islands",
            "Yggdrasill Path",
            "Hell's Heaven",
            "Birin T'Challa",
            "Royal Palace"
        ],
        "roles" : ["Vangaurd","Duelist","Strategist"],
        "char_to_role": [0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2]
    },
    "Overwatch": {
        "characters": [
            "Ana",
            "Ashe",
            "Baptiste",
            "Bastion",
            "Brigitte",
            "Cassidy",
            "DVA",
            "Doomfist",
            "Echo",
            "Genji",
            "Hanzo",
            "Hazard",
            "Illari",
            "Junker Queen",
            "Junkrat",
            "Juno",
            "Kiriko",
            "Lifeweaver",
            "Lucio",
            "Mauga",
            "Mei",
            "Mercy",
            "Moira",
            "Orisa",
            "Pharah",
            "Ramattra",
            "Reaper",
            "Reinhardt",
            "Roadhog",
            "Sigma",
            "Sojourn",
            "Soldier 76",
            "Sombra",
            "Symmetra",
            "Torbjorn",
            "Tracer",
            "Venture",
            "Widowmaker",
            "Winston",
            "Wrecking Ball",
            "Zarya",
            "Zenyatta"
        ],
        "maps": [
            "Antarctic Peninsula",
            "Busan",
            "Ilios",
            "Lijiang Tower",
            "Nepal",
            "Oasis",
            "Samoa",
            "Colosseo",
            "Esperanca",
            "New Queen Street",
            "Runasapi",
            "Blizzard World",
            "Eichewalde",
            "Holywood",
            "King's Row",
            "Midtown",
            "Numbani",
            "Paraiso"
        ],
        "roles": ["Tank", "Damage", "Support"],
        "char_to_role": [2,1,2,1,2,1,0,0,1,1,1,0,2,0,1,2,2,2,2,0,1,2,2,0,1,0,1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,2]
    },
    "League of Legends": {
        "characters": [
            "Aatrox",
            "Ahri",
            "Akali",
            "Akshan",
            "Alistar",
            "Ambessa",
            "Amumu",
            "Anivia",
            "Annie",
            "Aphelios",
            "Ashe",
            "Aurelion Sol",
            "Aurora",
            "Azir",
            "Bard",
            "Bel'Veth",
            "Blitzcrank",
            "Brand",
            "Braum",
            "Briar",
            "Caitlyn",
            "Camille",
            "Cassiopeia",
            "Cho'Gath",
            "Corki",
            "Darius",
            "Diana",
            "Ddraven",
            "Dr.Mundo",
            "Ekko",
            "Elise",
            "Evelynn",
            "Ezreal",
            "Fiddlesticks",
            "Fiora",
            "Fizz",
            "Galio",
            "Gangplank",
            "Garen",
            "Gnar",
            "Gragas",
            "Graves",
            "Gwen",
            "Hecarim",
            "Heimerdinger",
            "Hwei",
            "Illaoi",
            "Irelia",
            "Ivern",
            "Janna",
            "Jarvan IV",
            "Jax",
            "Jayce",
            "Jhin",
            "Jinx",
            "Kai'Sa",
            "Kalista",
            "Karma",
            "Karthus",
            "Kassadin",
            "Katarina",
            "Kayle",
            "Kayn",
            "Kennen",
            "Kha'Zix",
            "Kindred",
            "Kled",
            "Kog'Maw",
            "K'Sante",
            "LeBlanc",
            "Lee Sin",
            "Leona",
            "Lillia",
            "Lissandra",
            "Lucian",
            "Lulu",
            "Lux",
            "Malphite",
            "Malzahar",
            "Maokai",
            "Master Yi",
            "Mel",
            "Milio",
            "Miss Fortune",
            "Mordekaiser",
            "Morgana",
            "Naafiri",
            "Nami",
            "Nasus",
            "Mautilus",
            "Neeko",
            "Nidalee",
            "Nilah",
            "Nocturne",
            "Nunu & Willump",
            "Olaf",
            "Orianna",
            "Ornn",
            "Pantheon",
            "Poppy",
            "Pyke",
            "Qiyana",
            "Quinn",
            "Rakan",
            "Rammus",
            "Rek'Sai",
            "Rell",
            "Renata Glasc",
            "Renekton",
            "Rengar",
            "Riven",
            "Rumble",
            "Ryze",
            "Samira",
            "Sejuani",
            "Senna",
            "Seraphine",
            "Sett",
            "Shaco",
            "Shen",
            "Shyvana",
            "Singed",
            "Sion",
            "Sivir",
            "Skarner",
            "Smolder",
            "Sona",
            "Soraka",
            "Swain",
            "Sylas",
            "Syndra",
            "Tahm Kench",
            "Taliyah",
            "Talon",
            "Ttaric",
            "Teemo",
            "Thresh",
            "Tristana",
            "Trundle",
            "Tryndamere",
            "Twisted Fate",
            "Twitch",
            "Udyr",
            "Urgot",
            "Varus",
            "Vayne",
            "Veigar",
            "Vel'Koz",
            "Vex",
            "Vi",
            "Vieao",
            "Viktor",
            "Vladmir",
            "Volibear",
            "Warwick",
            "Wukong",
            "Xayah",
            "Xerath",
            "Xin Zhao",
            "Yasuo",
            "Yone",
            "Yorick",
            "Yuumi",
            "Zac",
            "Zed",
            "Zeri",
            "Ziggs",
            "Zilean",
            "Zoe",
            "Zyra"
        ],
        "maps": [
            "Summoner's Rift"
        ],
        "roles": ["Top", "Mid", "Bot", "Jungle", "Support"],
        "char_to_role": [
            0,1,1,1,4,0,3,1,1,2,2,1,1,1,4,3,4,4,4,4,2,0,1,0,2,3,3,2,0,3,3,3,2,3,0,1,1,0,0,0,0,3,0,3,0,1,0,0,3,4,3,0,0,2,2,2,2,
            4,3,1,1,0,3,0,3,3,0,2,0,1,3,4,3,1,2,4,4,0,1,4,3,1,4,2,0,4,1,4,0,4,4,3,2,3,3,0,1,0,3,4,4,1,0,4,3,3,4,4,0,3,0,0,1,2,
            3,4,4,0,3,0,3,0,0,2,3,2,4,4,4,1,1,4,1,3,4,0,4,2,0,0,1,2,3,0,2,2,1,4,1,3,3,1,1,0,3,3,2,1,3,1,1,0,4,3,1,2,2,4,1,3
        ]
    }
}