GAME_DATA = {
    "Valorant": {
        "characters": [
            "Brimstone",
            "Omen",
            "Viper",
            "Raze",
            "Cypher",
            "Sage",
            "Sova",
            "Phoenix",
            "Jett",
            "Breach",
            "Reyna",
            "Killjoy",
            "Skye",
            "Yoru",
            "Astra",
            "KAY/O",
            "Chamber",
            "Neon",
            "Fade",
            "Harbor",
            "Gekko",
            "Deadlock",
            "Iso",
            "Clove",
            "Vyse",
            "Tejo",
            "Waylay"
            ],
        "roles": ["Duelist", "Initiator", "Sentinel", "Controller"]
    },
    "Marvel Rivals":{
        "characters": [
            "Hulk",
            "Captain America",
            "Doctor Strange",
            "Groot",
            "Magneto",
            "Peni Parker",
            "The Thing",
            "Thor",
            "Venom",
            "Black Panther",
            "Black Widow",
            "Hawkeye",
            "Hela",
            "Human Torch",
            "Iron Fist",
            "Iron Man",
            "Magik",
            "Mister Fantastic",
            "Moon Knight",
            "Namor",
            "Psylocke",
            "Punisher",
            "Scarlet Witch",
            "Spider-Man",
            "Squirrel Girl",
            "Star-Lord",
            "Storm",
            "Winter Soldier",
            "Wolverine",
            "Adam Warlock",
            "Cloak and Dagger",
            "Invisible Woman",
            "Jeff the Land Shark",
            "Loki",
            "Luna Snow",
            "Mantis",
            "Rocket Raccoon"
        ],
        "roles" : [
            "Vangaurd",
            "Duelist",
            "Strategist"
        ]
    },
    "Overwatch": {
        "characters": [
            "Ana",
            "Ashe",
            "Bastion",
            "Brigitte",
            "Doomfist",
            "Echo",
            "Genji",
            "Hanzo",
            "Hazard",
            "Illari",
            "Junkrat",
            "Junker Queen",
            "Kiriko",
            "Lifeweaver",
            "Lúcio",
            "Mauga",
            "Cassidy",
            "Mei",
            "Mercy",
            "Orisa",
            "Pharah",
            "Reaper",
            "Reinhardt",
            "Roadhog",
            "Rammatra",
            "Sigma",
            "Sombra",
            "Sojourn",
            "Soldier: 76",
            "Symmetra",
            "Torbjörn",
            "Tracer",
            "Wrecking Ball",
            "Widowmaker",
            "Venture",
            "Zarya",
            "Zenyatta",
            "Juno",
            "Freja",
            "Aqua"
        ],
        "roles": ["Tank", "Damage", "Support"]
    },
    "League of Legends": {
        "characters": ["Ahri", "Garen", "Lux", "Zed"],
        "roles": ["Top", "Mid", "Jungle", "Support", "ADC"]
    }
}